services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - appnet

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: gemma3:4b
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - appnet

volumes:
  ollama_data:

networks:
  appnet: